---
- name: update the apt-cache
  apt: update_cache=yes 
  sudo: yes
  tags:
    - bower

- name: install bower 
  sudo: yes
  shell: npm install -g bower
  tags:
     - bower

- name: install frontend dependencies 
  sudo: no
  shell: bower install
  args:
     chdir: "{{ sites_dir }}/{{ project_name }}"
  tags:
     - bower 
