---
- name: Update code from remote repo 
  git: "{{ project_repo }}"
  sudo: no
  args:
      chdir: "{{ deploy_dir }}/{{ project_name }}"
  tags:
      - client
      - code

- name: Install/update requirement inside virtualenv
  sudo: no
  pip: virtualenv={{ virtualenvs_dir }}/{{ project_name }}-env 
       name=matriz
  tags:
      - client
      - dependencies

- name: Deploy client startup Script
  template: src=supervisord.j2
            dest=/etc/supervisor/conf.d/matriz-client.conf
            backup=yes
  tags:
     - client
     - supervisord

- name: Re-read the Supervisor config files and start app
  command: supervisorctl -c .supervisord.conf reread
- supervisorctl: name=matriz state=started
  tags:
     - client
     - supervisord
