- name: Disable internal sound card
  copy: src=config.txt dest=/boot/config.txt 
        owner=root 
        group=root 
        mode=644 
        backup=yes
  when: "{{ pi }}"
  tags:
    - pi

- name: Apply kernel cmdline hack for focusrite scarlet 2i2
  copy: src=cmdline.txt dest=/boot/cmdline.txt 
        owner=root 
        group=root 
        mode=644 
        backup=yes
  when: "{{ pi }}"
  tags:
    - pi
