---
- name: Generate locale
  command: locale-gen pt_PT.UTF-8
  tags:
      - locale

- name: Configure locale
  command: dpkg-reconfigure --frontend noninteractive locales
  environment:
      LANG: en_US.UTF-8
  tags:
      - locale

