---
- name: Add matriz repo key
  apt_key: url=http://matriz.stress.fm/deb_repo/matriz_deb.gpg.asc state=present 

- name: Add matriz repo
  apt_repository: repo='deb http://matriz.stress.fm/deb_repo jessie main' state=present
  tags:
      - packages
      - apt

- name: update the apt-cache
  apt: update_cache=yes
  tags:
      - cache 
      - packages 

- name: install common package dependencies
  apt: >
        pkg={{ item }}  
        state=latest
        force=yes
  with_items:
	- jackd2 
    - python-gst-1.0 
    - libgstrtspserver-1.0
    - gstreamer1.0-plugins-bad 
    - libgstreamer-plugins-bad1.0
    - python-pip
    - openssl
    - libssl-dev
    - supervisor
    - jackd2 
    - qjackctl 
    - jackd-tools

  tags:
      - packages 

- name: safe upgrade 
  apt: upgrade=safe force=yes
  tags:
      - upgrade 
      - packages
