---
- name: Install packages via pip
  pip: name={{ item }}
  sudo: yes 
  with_items:
    - virtualenv
    - virtualenvwrapper
  tags:
      - web
      - venv

- name: create the virtualenvwrapper dir if not present
  file: path={{ virtualenvs_dir }} owner={{ deploy_user }} state=directory
  sudo: no
  tags:
      - web
      - venv

- name: Add virtualenvwrapper init1 to the bash profile
  lineinfile: dest=/home/{{ deploy_user }}/.profile line="export WORKON_HOME=~/virtualenvs"
  sudo: no
  tags:
      - web
      - venv

- name: Add virtualenvwrapper init to the bash profile
  lineinfile: dest=/home/{{ deploy_user }}/.profile line="source /usr/local/bin/virtualenvwrapper.sh"
  sudo: no
  tags:
      - web
      - venv

- name: create the project virtualenv
  command: virtualenv {{ virtualenvs_dir }}/{{ project_name }}-env --no-site-packages
  sudo: no
  args:
      creates: "{{ virtualenvs_dir }}/{{ project_name }}-env/bin/activate"
  tags:
      - web
      - venv

- name: Pull or update the source
  sudo: no
  shell: git pull
  args:
      chdir: "{{ deploy_dir }}/{{ project_name }}"
  tags:
      - venv 

- name: Install packages required by the app inside virtualenv
  sudo: no
  pip: virtualenv={{ virtualenvs_dir }}/{{ project_name }}-env 
      requirements={{ deploy_dir }}/{{ project_name }}/requirements/production.txt
  tags:
      - web
      - venv

- name: Copy/Create the postactivate env file 
  template: src=postactivate.j2
            dest={{ virtualenvs_dir }}/{{ project_name }}-env/bin/postactivate
            owner={{ deploy_user }}
            group={{ deploy_user }}
            mode=0740
            backup=yes
  tags:
      - web
      - venv 
      - postactivate 

