- name: set swap_file variable
  set_fact:
    swap_file: /{{ swap_space }}.swap
  tags:
    - swap

- name: check if swap file exists
  stat:
    path: "{{ swap_file }}"
  register: swap_file_check
  tags:
    - swap

- name: create swap file
  sudo: yes
  command: fallocate -l {{ swap_space }} {{ swap_file }}
  when: not swap_file_check.stat.exists
  tags:
    - swap

- name: set permissions on swap file
  sudo: yes
  file:
    path: "{{ swap_file }}"
    mode: 0600
  tags:
    - swap

- name: format swap file
  sudo: yes
  command: mkswap {{ swap_file }}
  when: not swap_file_check.stat.exists
  tags:
    - swap

- name: add to fstab
  sudo: yes
  lineinfile:
    dest: /etc/fstab
    regexp: "{{ swap_file }}"
    line: "{{ swap_file }} none swap sw 0 0"
  tags:
    - swap

- name: turn on swap
  sudo: yes
  command: swapon -a
  tags:
    - swap

- name: set swapiness
  sudo: yes
  sysctl:
    name: vm.swappiness
    value: "1"
  tags:
    - swap
